database: mysql

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/bookstore?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC"
    username: "root"
    password: "root"
    initialization-mode: always
